### ISSUE TITLE
Clicking on balance or send max shouldn't be active when android keyboard is opened

### ISSUE THREAD

**Issue by bitcoinuser** [BlakeKaufman/BlitzWallet#291]
Hi,

Clicking on balance or send max shouldn't be active when android keyboard is opened. Maybe the balance and send max button should show as gray color, to demonstrate that the buttons are inactive when android keyboard is opened.

https://github.com/user-attachments/assets/3a1508de-6dc9-4e8f-8c3b-f5b0b22efc76

**Comment by BlakeKaufman** [comment]
Fixed this

**Comment by bitcoinuser** [comment]
> Fixed this

Still happens on custom amount on receive page:

https://github.com/user-attachments/assets/cb2c75c5-3dec-4eaa-bcca-fe333a994c4b
